Perforación_Y_Voladuras_Adolfitos/Controllers/EmpContratistaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
//////////////
using PYVA.Interfaces.Interfaces;
using PYVA.Models;
using Validators.EmpContratistaValidators;

namespace Perforación_Y_Voladuras_Adolfitos.Controllers
{
    public class EmpContratistaController : Controller
    {
        private InterfaceEmpContratista repository;
        private EmpContratistaValidator validator;

        public EmpContratistaController(InterfaceEmpContratista repository, EmpContratistaValidator validator)
        {
            this.repository = repository;
            this.validator = validator;
        }

        [HttpGet]
        public ViewResult Index(string query = "")
        {
            var datos = repository.ByQueryAll(query);
            return View("Inicio", datos);
        }

        [HttpGet]
        public ViewResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        public ActionResult Create(EmpContratista empContratista)
        {
            validator.Execute(empContratista);
            validator.errors.ToList().ForEach(x => ModelState.AddModelError(x.Key, x.Value));

            if (ModelState.IsValid)
            {
                repository.AddEmpContratista(empContratista);
                TempData["UpdateSuccess"] = "Se Guardo Correctamente";

                return RedirectToAction("Index");
            }
           
            return View("Create", empContratista);
        }

        [HttpGet]
        public ViewResult Edit(int id)
        {
            var data = repository.FindEmpContratista(id);
            return View("Edit", data);
        }

        [HttpPost]
        public ActionResult Edit(EmpContratista empContratista)
        {
            validator.Execute(empContratista);
            validator.errors.ToList().ForEach(x => ModelState.AddModelError(x.Key, x.Value));

            if (ModelState.IsValid)
            {
                repository.UpdateEmpContratista(empContratista);
                TempData["UpdateSuccess"] = "Se actualizo correctamente";
                return RedirectToAction("Index");
            }

            var data = repository.FindEmpContratista(empContratista.Id);
            return View("Edit",data);
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            repository.DeleteEmpContratista(id);
            TempData["UpdateSuccess"] = "Se Eliminó Correctamente";
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ViewResult Details(int id)
        {
            var data = repository.FindEmpContratista(id);
            return View("Details", data);
        }


    }
}

Perforación_Y_Voladuras_Adolfitos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>@ViewBag.Title - Perforacion y Voladura Adolfitos</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <script type="text/javascript" src="/scripts/jquery.min.js"></script>
    <script type="text/javascript" src="/scripts/moment.min.js"></script>
    <script type="text/javascript" src="/scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="/scripts/bootstrap-datetimepicker.js"></script>


    <link rel="stylesheet" href="/Content/bootstrap-datetimepicker.css" />

    <script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker({
                format: 'DD/MM/YYYY'
            });
            $('#datetimepicker2').datetimepicker({
                format: 'DD/MM/YYYY'
            });
            $('#datetimepicker3').datetimepicker({
                format: 'MM/DD/YYYY'
            });
            $('#datetimepicker4').datetimepicker({
                format: 'MM/DD/YYYY'
            });
        });
    </script>

    @*<script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker();
        });
        </script>*@

</head>

<body>
    @RenderSection("featured", required: false)


    @RenderSection("scripts", required: false)
    <!-- Fixed navbar -->
    <nav  class="navbar navbar-wrapper navbar-inverse animate">
        <div class="container container-container ">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">P.Y.V.A.S. SAC</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active">@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Trabajador", "Index", "Trabajador")</li>
                    <li>@Html.ActionLink("Proyecto", "Index", "Proyecto")</li>
                    <li>@Html.ActionLink("Epp", "Index", "Epp")</li>
                    <li>@Html.ActionLink("E.Contratista", "Index", "EmpContratista")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="../navbar/">Default</a></li>
                    <li><a href="../navbar-static-top/">Static top</a></li>
                    <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </nav>

    <div>
        <hr />
        <hr />
    </div>

    <div class="container">
        @RenderBody()

    </div>

    <footer class="bs-footer" role="contentinfo">
        <div class="container text-center">
            <hr />
            <div class="well well-sm">
                <p>&copy; @DateTime.Now.Year - Desarrollado por <a hreft="http://adolfitossoft.com">ADOLFITOSSOFT</a> </p>
            </div>
            <div id="top-social-profiles">

                <a href="http://twitter.com/" target="_blank">
                    <img title="Twitter" alt="Twitter" src="http://www.geomex.es/wp-content/themes/Smart/images/social-profiles/twitter.png" /></a>
                <a href="http://facebook.com/" target="_blank">
                    <img title="Facebook" alt="Facebook" src="http://www.geomex.es/wp-content/themes/Smart/images/social-profiles/facebook.png" /></a>
                <a href="http://www.linkedin.com/" target="_blank">
                    <img title="LinkedIn" alt="LinkedIn" src="http://www.geomex.es/wp-content/themes/Smart/images/social-profiles/linkedin.png" /></a>
                <a href="http://www.geomex.es/feed/" target="_blank">
                    <img title="RSS Feed" alt="RSS Feed" src="http://www.geomex.es/wp-content/themes/Smart/images/social-profiles/rss.png" /></a>
                <a href="mailto:your@email.com" target="_blank">
                    <img title="Email" alt="Email" src="http://www.geomex.es/wp-content/themes/Smart/images/social-profiles/email.png" /></a>

            </div>
        </div>
    </footer>
</body>
</html>

Perforación_Y_Voladuras_Adolfitos/Views/Shared/layer22.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>@ViewBag.Title - Perforacion y Voladura Adolfitos</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">




    <script type="text/javascript" src="/scripts/jquery.min.js"></script>
    <script type="text/javascript" src="/scripts/moment.min.js"></script>
    <script type="text/javascript" src="/scripts/bootstrap.min.js"></script>
    <script type="text/javascript" src="/scripts/bootstrap-datetimepicker.js"></script>
    <!-- include your less or built css files  -->
    <!--
    bootstrap-datetimepicker-build.less will pull in "../bootstrap/variables.less" and "bootstrap-datetimepicker.less";
    or -->
    <link rel="stylesheet" href="/Content/bootstrap-datetimepicker.css" />

    <script type="text/javascript">
        $(function () {
            $('#datetimepicker1').datetimepicker({
                format: 'DD/MM/YYYY'
            });
            $('#datetimepicker2').datetimepicker({
                format: 'DD/MM/YYYY'
            });
            $('#datetimepicker3').datetimepicker({
                format: 'MM/DD/YYYY'
            });
            $('#datetimepicker4').datetimepicker({
                format: 'MM/DD/YYYY'
            });
        });
    </script>

</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Project name</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>
                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">Nav header</li>
                            <li><a href="#">Separated link</a></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="../navbar/">Default</a></li>
                    <li><a href="../navbar-static-top/">Static top</a></li>
                    <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>

    <div class="container">

        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>

    </div> <!-- /container -->
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET MVC</p>
            </div>
        </div>
    </footer>


    @RenderSection("scripts", required: false)
</body>
</html>